config/routes.rb
require 'sidekiq/web'
Tracker::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :devices do
    member do
      get :show_map
    end
    resources :logs do
      collection do
        delete :clear
      end
    end
    resources :fences do
      member do
        post :enable
      end
    end
  end

  resources :logs do
    collection do
      post :device_create
      post :device_create_bs
      post :device_create_gps
      get :device_create_gps
      get :list_special_logs
      get :new_special_log
      post :create_special_log
    end
    member do
      get :bs_detail
      delete :delete_special_log
    end
  end

  resources :change_logs
  resources :feedbacks

  root :to => 'welcome#index'

end

app/models/fence.rb
# encoding: utf-8
require 'array'
require 'math'
class Fence
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String, default: "未命名电子围栏"
  field :points, type: Array, default: []
  field :enabled, type: Boolean, default: true

  LONGITUDE_BASE = 0.005
  LATITUDE_BASE = 0.002

  belongs_to :device

  def points_center
    latitude_ary = self.points.map { |e| e[0] }
    longitude_ary = self.points.map { |e| e[1] }
    return [latitude_ary.mean, longitude_ary.mean]
  end

  def points_zoom
    latitude_ary = self.points.map { |e| e[0] }
    longitude_ary = self.points.map { |e| e[1] }
    latitude_diff = latitude_ary.max - latitude_ary.min
    longitude_diff = longitude_ary.max - longitude_ary.min
    zoom = []
    zoom << (longitude_diff == 0 ? 18 : (18 - Math.my_log(2, longitude_diff / LONGITUDE_BASE)).floor)
    zoom << (latitude_diff == 0 ? 18 : (18 - Math.my_log(2, latitude_diff / LATITUDE_BASE)).floor)
    zoom << 18
    @zoom = zoom.min
  end
end

app/controllers/fences_controller.rb
# encoding: utf-8
require 'string'
class FencesController < ApplicationController

  def index
    @device = Device.find_by_id(params[:device_id])
    @fences = @device.fences.desc(:generated_at)
  end

  def create
    fence = Fence.create(params[:fence])
    device = Device.find(params[:device_id])
    device.fences << fence
    respond_to do |format|
      format.html
      format.json do
        render json: { success: true }
      end
    end
  end

  def new
    @device = Device.find_by_id(params[:device_id])
    @logs = @device.eff_logs.asc(:created_at)
    @logs = @logs.select { |e| e.lat_offset.present? && e.lng_offset.present? }
    if @logs.blank?
      @center = [39.916527,116.397128]
      @zoom = 8
    else
      @center = @device.log_center
      @zoom = @device.log_zoom
    end
  end

  def enable
    @fence = Fence.find(params[:id])
    @fence.enabled = params[:enabled].to_s == "true"
    @fence.save
    respond_to do |format|
      format.html
      format.json do
        render json: { success: true }
      end
    end
  end

  def show
    @device = Device.find(params[:device_id])
    @fence = Fence.find(params[:id])
    @points = @fence.points
    if @points.blank?
      @center = [39.916527,116.397128]
      @zoom = 8
    else
      @center = @fence.points_center
      @zoom = @fence.points_zoom
    end
  end

  def update
    device = Device.find(params[:device_id])
    fence = Fence.find(params[:id])
    fence.update_attributes(params[:fence])
    respond_to do |format|
      format.html
      format.json do
        render json: { success: true }
      end
    end
  end
end

app/views/fences/index.haml
- content_for :app_head do
  = javascript_include_tag "pages/fences-bundle"
  = stylesheet_link_tag "pages/fences-bundle", :media => "all"

.container
  .col-sm-8.col-sm-offset-2
    - if @fences.blank?
      %h4
        没有符合条件的电子围栏,
    - else
      .table-responsive
        %table#fence-table.table.table-striped
          %tr 
            %th 名称
            %th 创建时间
            %th.enable-column 启用
          - @fences.each do |f|
            %tr               
              %td
                = link_to f.name, device_fence_path(@device, f)
              %td= f.created_at
              %td.enable-column
                - if f.enabled
                  %input.enable-checkbox{data: {"fence-id" => f.id.to_s, "device-id" => @device.id.to_s}, checked: "checked", name: "enable-checkbox", type: "checkbox"}/
                - else
                  %input.enable-checkbox{data: {"fence-id" => f.id.to_s, "device-id" => @device.id.to_s}, name: "enable-checkbox", type: "checkbox"}/

    = link_to "创建电子围栏", {controller: "fences", action: "new"}, :class => 'btn btn-primary btn-sm'

app/views/fences/new.haml
- content_for :app_head do
  = javascript_include_tag "http://map.qq.com/api/js?v=2.exp&libraries=drawing"
  = javascript_include_tag "pages/fences-map-bundle"
  = stylesheet_link_tag "pages/fences-map-bundle", :media => "all"
  :javascript
    window.center = ['#{@center[0]}', '#{@center[1]}']
    window.zoom = '#{@zoom}'
    window.action = '#{controller.action_name}'

#container
  .edit-div
    .form-inline
      .edit-left-group
        #fence-name.form-group
          %input{placeholder: "名称", type: "text", class: "form-control"}/
        %label#fence-enabled.checkbox
          %input{type: "checkbox"}/
          启用
      .edit-right-group
        %a#fence-reset.btn.btn-default{href: "#", "aria-hidden" => "true"} 重置
        = link_to "返回", device_fences_path(@device) , :class => 'btn btn-default'
        %a#fence-ok.btn.btn-default.btn-primary{href: "#", data: {"device-id" => @device.id.to_s}, "aria-hidden" => "true"} 确定
  #map-div

app/views/fences/show.haml
- content_for :app_head do
  = javascript_include_tag "http://map.qq.com/api/js?v=2.exp&libraries=drawing"
  = javascript_include_tag "pages/fences-map-bundle"
  = stylesheet_link_tag "pages/fences-map-bundle", :media => "all"
  :javascript
    window.center = ['#{@center[0]}', '#{@center[1]}']
    window.zoom = '#{@zoom}'
    window.action = '#{controller.action_name}'
    window.points = "#{(@fence.points.map { |e| e.join(',') }).join('-')}"

#container
  .edit-div
    .form-inline
      .edit-left-group
        #fence-name.form-group
          %input{placeholder: "名称", type: "text", value: @fence.name, class: "form-control"}/
        %label#fence-enabled.checkbox
          - if @fence.enabled
            %input{type: "checkbox", checked: "true"}/
          - else
            %input{type: "checkbox"}/
          启用
      .edit-right-group
        %a#fence-reset.btn.btn-default{href: "#", "aria-hidden" => "true"} 重置
        = link_to "返回", device_fences_path(@device) , :class => 'btn btn-default'
        %a#fence-update.btn.btn-default.btn-primary{href: "#", data: {"device-id" => @device.id.to_s, "fence-id" => @fence.id.to_s}, "aria-hidden" => "true"} 更新
  #map-div